Kkwolek98/psm-project

src/App.vue
src/components/SearchBar.vue
src/views/FindItem.vue
src/views/LoginPage.vue

Closes #23

---

src/components/HeaderTitle.vue

header title responsiveness fixed

---

src/App.vue

body padding fix

---

src/components/KcalMeter.vue
src/components/MealList.vue
src/views/Jurnal.vue

round numbers

---

src/router/index.js
src/views/Journal.vue

fixed Journal typo

---

src/components/KcalMeter.vue

red gradient if kcal meter > 95

---

src/App.vue
src/components/MealList.vue
src/views/DayView.vue

day view fixed on smaller devices

---

src/components/MealList.vue
src/components/SearchBar.vue
src/views/AddItem.vue
src/views/FindItem.vue

redirect to /day after adding item + minor css fixes

---

package-lock.json
package.json
src/views/About.vue

about page done

---

src/App.vue
src/components/Navigation.vue

fixed navigation display

---

src/views/SignUpPage.vue

fixed sign up box size

---

src/components/MacroDialog.vue
src/components/MealDialog.vue
src/components/MealList.vue
src/components/Navigation.vue
src/router/index.js
src/views/DayView.vue

Macroelements && Meal details

---

src/views/DayView.vue

date fix dayview

---

src/components/MealList.vue

clickable dla mealsów

---

README.md
package-lock.json
package.json

Rename app to FoodLog

---

src/router/index.js

dont require auth on /about

---

src/views/FindItem.vue

Remove mention of barcode

---

src/views/FindItem.vue

random motivational quote on item add

---

src/views/DayView.vue

added clickable class to macroelements

---

src/firebase/food.js
src/views/Profile.vue

friend list

---

src/views/LoginPage.vue

change path after login

---

src/views/About.vue
src/views/LoginPage.vue

fix bug text about nad komponentem

---

src/firebase/profile.js
src/views/Profile.vue

added timeout to saving profile

---

src/views/Profile.vue

calculate kcal goal

---

src/components/SearchBar.vue

add label to search bar in findItem
